### ISSUE TITLE
Window too large for screens smaller than 1920x1080

### ISSUE THREAD

**Issue by laundmo** [stevenang/randomness_testsuite#1]
im currently trying to use this on my laptop with a resolution of 1366x768 and i cant reach th lower tests and the other buttons.

**Comment by stevenang** [comment]
Hello. Thanks for using this program and the feedback.  

The program was originally created using my Mac system and I never test it using Windows system.  I will try to check this with the windows system and see how to fix this.

**Comment by carkas** [comment]
Hello Dear 
I really don't know how to for thank you. Because NIST Test Suite was very Difficult to  Run it,
But your python code very simple and understandable code.
I use your Test benchmark in my Researches and certainly reference to your Randomness test Suite.
I like, I have your email Address, if it possible please send it to me.
my email:  mo.zeynali@gmail.com

Best Regards 
mohammad zeynali

**Comment by Obscurial** [comment]
Hey, I have the same issue, would love to have an update. Thanks for making this.

**Comment by stevenang** [comment]
> Hey, I have the same issue, would love to have an update. Thanks for making this.

Hello, I have updated the code now it can displayed at the resolution of 1600 x 900.  Please check if it is ok with you.

**Comment by stevenang** [comment]
> im currently trying to use this on my laptop with a resolution of 1366x768 and i cant reach th lower tests and the other buttons.

Hello.  The best right now is can be displayed at 1600 x 900.  I still need to find out the way and not compromising the whole displayed.  The resolution you given is still little bit difficult for me to adjust.

**Comment by stevenang** [comment]
> im currently trying to use this on my laptop with a resolution of 1366x768 and i cant reach th lower tests and the other buttons.

Hello, I created a new layout to solve your problem.  Can you check if the new version is working with your environment or not.
