### ISSUE TITLE
[Cumulative Sums Test] Add/Sub -1 after division instead of before leads to wrong result for test.

### ISSUE THREAD

**Issue by LukasMarckmiller** [stevenang/randomness_testsuite#19]
According to the NIST Standard 1 needs to be subtracted/added before the division.
![Screenshot_2024-04-19_09-37-58](https://github.com/stevenang/randomness_testsuite/assets/18208274/d0fd8500-1821-4ca5-a5e2-1fa0351dc7a0)

This is not the case for following lines:
https://github.com/stevenang/randomness_testsuite/blob/7147879859d095a4cac63962efd7a19d4874a630/CumulativeSum.py#L54-L55

It should be:
```python
start = int(floor(0.25 * floor(-length_of_binary_data / abs_max + 1)))
end = int(floor(0.25 * floor(length_of_binary_data / abs_max - 1)))
```
This is correct for the second sum though:
https://github.com/stevenang/randomness_testsuite/blob/7147879859d095a4cac63962efd7a19d4874a630/CumulativeSum.py#L62-L63

**Comment by LukasMarckmiller** [comment]
Current:
13. Cummulative Sums (Forward) Test (1.0, True)
14. Cummulative Sums (Reverse) Test (1.0, True)

Fixed:
13. Cummulative Sums (Forward) Test (2.2319712527895903e-302, False)
14. Cummulative Sums (Reverse) Test (2.2319712527895903e-302, False)

I can provide the test data (private msg) if needed.

**Comment by alexb5dh** [comment]
Can this issue be closed, given that issue [was fixed](https://github.com/stevenang/randomness_testsuite/commit/2ec11664003889eb7bb68642260a48ca93fe4fe2)?
