### ISSUE TITLE
reading from a string file shows empty results, although the console in the background works

### ISSUE THREAD

**Issue by laundmo** [stevenang/randomness_testsuite#2]
im currently trying to use this on a string file, and when i select and run all the tests it says that its finished, but the fields stay empty.

**Comment by laundmo** [comment]
apparently it doesnt show anything when you use another file type

**Comment by stevenang** [comment]
Hello there

Good morning.
Yes, this program only reads a numeric input.
Other file type (like text files) is not supported yet.

Thank you and good day.

Sincerely yours,

Steven Ang
