### ISSUE TITLE
ERROR Runtime

### ISSUE THREAD

**Issue by TourajOstovari** [stevenang/randomness_testsuite#23]
![Screenshot 2024-07-20 141100](https://github.com/user-attachments/assets/1d5814e6-ffc1-4822-850f-b0b6797d3722)
Please fix this issue!

**Comment by LukasMarckmiller** [comment]
[Pull Request](https://github.com/stevenang/randomness_testsuite/pull/22)

**Comment by stevenang** [comment]
The fix was merged to main already
